#!/bin/sh /etc/rc.common

START=21
STOP=89

USE_PROCD=1

start_service() {
        procd_open_instance
        procd_set_param command /opt/clash/bin/clash -d /opt/clash
        procd_set_param respawn
        procd_close_instance

        uci add_list dhcp.@dnsmasq[0].server='127.0.0.1#7874'
        uci commit
}

stop_service() {
        uci delete dhcp.@dnsmasq[0].server
        uci commit
}
